### ISSUE TITLE
Missing <?php opening tag on atkinson.kiwi

### ISSUE THREAD

**Issue by manuelsucco** [merlinblack/NigeLib#1]
Hi Nigel,

I don't know if this is the right place to note this, but the wonderful description you give on [your blog](https://www.atkinson.kiwi/programming/creating-phar-cli-programs.html) is missing a `<?php` opening tag when you first create your own stub code (last code block before the section titled **"A bigger example with Composer"**). In PharBuilder.php the tag is there on line 147.

Omitting it leads to unclear syntax errors when executing the resulting phar file.

Thanks for writing this!
Cheers, Manuel

**Comment by merlinblack** [comment]
Nice catch! Thanks, I'll update it shortly.

**Comment by merlinblack** [comment]
Fixed! :-)
